# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
name: clfcs-test-harness
services:
  clfcs-th:
    image: ghcr.io/methodsbdt/clfcs-th:main
    hostname: clfcs-th
    ports:
      - 8082:8080
    networks:
      - clfcs-th-network

  vtn:
    image: ghcr.io/methodsbdt/clfcs-vtn:main
    hostname: vtn
    environment:
      - BASE_URI=http://vtn:8080/openadr3/3.1.0
      - CLEAN_START=true
      - STORAGE_IMPLEMENTATION=IN_MEMORY
    ports:
      - 8081:8080
    networks:
      - clfcs-th-network

networks:
  clfcs-th-network:
    name: clfcs-th-network
    external: false
    driver: bridge
